// @ts-check
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';

// https://astro.build/config
export default defineConfig({
	site: 'https://jsonbeam.com',
	output: 'static',
	// Sitemap is generated by src/pages/sitemap.xml.ts (data-driven from
	// FOOTER_NAV) rather than @astrojs/sitemap, so /sitemap.xml is one canonical
	// file with a single source of truth.
	vite: {
		plugins: [tailwindcss()],
		optimizeDeps: {
			// Pre-bundle these at server start so they don't trigger re-optimisation
			// (and the resulting full-page reload) the first time a query is run.
			// jmespath is CJS-only; jsonpath-plus has a browser ESM build but Vite
			// still needs to discover it up front to avoid the "outdated dep" reload.
			include: ['jsonpath-plus', 'jmespath'],
		},
	},
});
